# Generated by Django 2.2 on 2019-04-30 03:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_name', models.CharField(max_length=128, null=True)),
                ('award_level', models.CharField(max_length=16)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('hold_time', models.DateField()),
                ('organizer', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingInfo',
            fields=[
                ('competition_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=16)),
                ('level_title', models.CharField(max_length=16)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('clazz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.Class')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=None, null=True)),
                ('award_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.AwardRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=32)),
                ('field_model', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mapping_model', django.contrib.postgres.fields.jsonb.JSONField()),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to='api.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=256)),
                ('award_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AwardRecord')),
                ('recognition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api.Recognition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('hold_time', models.DateField()),
                ('organizer', models.CharField(max_length=128)),
                ('award_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition_record', to='api.AwardRecord')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_records', to='api.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='rating_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition', to='api.RatingInfo'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.Subject'),
        ),
        migrations.CreateModel(
            name='AwardStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AwardRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
        migrations.AddField(
            model_name='awardrecord',
            name='students',
            field=models.ManyToManyField(related_name='award_records', through='api.AwardStudentRelation', to='api.Student'),
        ),
        migrations.AddField(
            model_name='awardrecord',
            name='submit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardrecord',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Teacher'),
        ),
    ]
