# Generated by Django 2.2 on 2019-05-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='award_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.AwardRecord'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PASSED', 'Passed'), ('NOT_PASS', 'NotPass')], default='WAITING', max_length=12),
        ),
    ]
