# Generated by Django 2.2 on 2019-05-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190505_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rating_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='api.RatingInfo'),
        ),
    ]
