# Generated by Django 2.2 on 2019-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190506_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardrecord',
            name='main_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_award_records', to='api.Student'),
        ),
    ]
